# Generated by Django 3.1 on 2020-08-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, default='writer_default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, default='book_default.jpg', null=True, upload_to=''),
        ),
    ]
