# Generated by Django 3.1 on 2020-08-19 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bookies', '0002_auto_20200815_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'get_latest_by': 'id'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'get_latest_by': 'id'},
        ),
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, default='writer_default.jpg', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, default='book_default.jpg', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
