# Generated by Django 3.1 on 2020-08-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookies', '0003_auto_20200819_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.ManyToManyField(to='Bookies.Order'),
        ),
    ]
