# Generated by Django 3.1.2 on 2020-10-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookies', '0004_book_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, to='Bookies.Order'),
        ),
    ]
