# Generated by Django 3.1.2 on 2020-12-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookies', '0005_auto_20201003_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
